### ISSUE TITLE
TypeLevel constraints not working with Stackage lts-15.1

### ISSUE THREAD

**Issue by cdfa** [louispan/data-distinct#10]
Hi, I copied the following from the tests (and added all the GHC extensions):

```
test = let y = (5 :: Int) ./ False ./ Tagged @Foo 'X' ./ Tagged @"Hello" (6 :: Int) ./ nil in
  grab @(Tagged Foo _) y
```

Using Stackage `lts-15.1`, this gives me a type error:
```
Error:(33, 3) warning: [-Wdeferred-type-errors]
    • Could not deduce: Data.Diverse.TypeLevel.Internal.UniqueImpl
                          '[Int, Bool, Tagged Foo Char, Tagged "Hello" Int]
                          (Tagged Foo _0)
                          '[Tagged Foo Char, Tagged "Hello" Int]
        arising from a use of ‘grab’
    • In the expression: grab @(Tagged Foo _) y
      In the expression:
        let
          y = (5 :: Int)
                ./ False ./ Tagged @Foo 'X' ./ Tagged @"Hello" (6 :: Int) ./ nil
        in grab @(Tagged Foo _) y
      In an equation for ‘test’:
          test
            = let
                y = (5 :: Int)
                      ./ False ./ Tagged @Foo 'X' ./ Tagged @"Hello" (6 :: Int) ./ nil
              in grab @(Tagged Foo _) y
    • Relevant bindings include
        test :: Tagged Foo _0
          (bound at /home/cdfa/Projects/compiler-construction/ssplc/src/SsmGeneration.hs:32:1)
```

**Comment by louispan** [comment]
Hi, thank you for reporting this. Unfortunately, the type inference is not smart enough to realize that the only type with `Tagged @Foo` is `Tagged @Foo Char`.

The reason why the original test case works in `grab @(Tagged Foo _) y \`shouldBe\` Tagged @Foo 'X'`, is because the comparison to `Tagged @Foo 'X'` gives enough clues to the type inferencer to resolve the type.

I'm not sure but, it may be possible to add more functional dependencies specialised for Tagged to data-diverse so that it will work for your test case, but this is not a priority for me right now.

If you are keen, you could try - pull requests are welcome.

**Comment by cdfa** [comment]
Thank you for responding so quickly!

> The reason why the original test case works in `grab @(Tagged Foo _) y ``shouldBe`` Tagged @foo 'X'`, is because the comparison to `Tagged @foo 'X'` gives enough clues to the type inferencer to resolve the type.

Ah okay, I thought it might be something like that. I managed to get my example working by adding a type annotation:
```
test = let y = (5 :: Int) ./ False ./ Tagged @Foo 'X' ./ Tagged @"Hello" (6 :: Int) ./ nil in
  grab @(Tagged Foo _) y :: Tagged Foo Char
```

Anyway, I think I'll be using the lenses from `data-diverse-lens` (although there is a small issue: https://github.com/louispan/data-diverse-lens/issues/1) for most of the field getting. Thanks for the help!
