### ISSUE TITLE
Impossible not impossible?

### ISSUE THREAD

**Issue by dwincort** [louispan/data-distinct#4]
I find your use of zilch/impossible a little confusing.  I would have presumed that `Which '[]` is uninhabited -- that it is a zero type -- and that as such, one could trivially `diversify` it into any other `Which` type.  Instead, it *is* inhabited (by the value `zilch`), and it's a type error to do anything with it.  Wouldn't it make more sense to *not* have a value `zilch` and instead have a function like:
```
impossible :: Which '[] -> a
```
Then, if one ever `trial`s into a case expecting a `Which '[]`, they can trivially satisfy it with `impossible`, and `diversify` and other such functions could handle `Which '[]` occurrences similarly.

**Comment by louispan** [comment]
I see so it follows `Void`'s `absurd`.
I explicitly didn't want to allow `Which '[]` to be `diversify`ed into any other `Which` type, because a `Which` with a nonempty type list is always inhabited; to `diverisfy` `Which '[]` will break that contract.
I will experiment with your suggestion `impossible`/`aburd` and add it in.

**Comment by louispan** [comment]
I've added `impossible` in this commit https://github.com/louispan/data-diverse/commit/7d57c77dc9b9b747e8b19dec2b10a4bb8c00808a

Is this sufficient for your needs?

If so, I'll upload a new version to hackage

**Comment by louispan** [comment]
Ah, I have to remove 'zilch' as well

**Comment by dwincort** [comment]
While I understand your concern about `diversify`ing `Which '[]` into another type, once you remove `zilch`, it's actually no longer problematic.  After all, there will be no way to construct a value of type `Which '[]` -- the type will be uninhabited -- so there will be no value that you can *actually* `diversify` to go from `Which '[]` to `Which` anything else.

That said, by allowing one to `Diversify` the `Which '[]` type (I'm talking about the type level here, not the value level), then the type theory will work out nicely.  Indeed, `Which '[]` will be the identity type -- the "Zero" -- over the `Which` sum type, exactly as one would expect.

**Comment by dwincort** [comment]
Also, thank you for your quick reply and your willingness to help!

**Comment by dwincort** [comment]
In practice, you might need to code with a "value" of type `Which '[]`, for instance when using `trial0`.  I imagine it would look something like:
```
let x = pickOnly 3 :: Which '[Int]
let n = case trial0 x of
  Left y -> impossible y
  Right y -> y
n `shouldBe` 3
```
Essentially, `impossible y` here is dead code.

As far as diversifying values of type `Which '[]`, here's an example of why this will never happen.  Say you allow it.  Then, I could write the following:
```
absurdList :: [Which '[]]
```
and I could diversify this:
```
reasonableList :: [Which '[Int, String]]
reasonableList = map diversify absurdList
```
This may seem alarming, but the value `absurdList` is guaranteed to be empty because there is no way for me to populate it with values.

In fact, the instance needed for allowing `Diversify` is trivial:
```
instance Reduce (Which '[]) (Switch c '[]) r where
  reduce _ = impossible
```
Obviously, the function will never be called on an actual value because there can be no values of the type `Which '[]`

**Comment by louispan** [comment]
Okay, Which '[] is now truly uninhabited
https://github.com/louispan/data-diverse/commit/359c6029b86708f5555523bc042d77233277f9e2

What do you think?

**Comment by louispan** [comment]
Sorry, I didn't see your comments above re: diversifying Which '[]. Give me a moment to think about them.

**Comment by louispan** [comment]
I think I understand. Because zilch is removed, so Which '[] is truly uninhabited, then type level Diversify is safe. It's just an example of absurd/impossible' "given a falsehood, anything follows"

With impossible/absurd you can already convert '[Which '[]]' to [anything]' with 'fmap impossible'

I like it. I'll make the change to add Which '[] to Diversify after work (in 9 hours time)

**Comment by dwincort** [comment]
Awesome!  I'm looking forward to it :)

**Comment by louispan** [comment]
Just out of interest, may I ask what you are using data-diverse for?

**Comment by dwincort** [comment]
I'm writing a big event-based simulator, and I'm trying to make it really type-safe.  Each event is a `Which`, and you write event handlers by putting together a set of functions that all have the same output: a `Many` where each element is essentially of the type `e -> Output` where `e` is in the `Which`.  It gets a little tricky because each handler may also want to produce events, so I need to keep track of which events get produced.  (Incidentally, it's here that I ran into the `diversify` problem---some handlers produce nothing, so the type of their produced events is `Which '[]`, and when I merge them with handlers that do produce something, I need to `diversify` the two produced event streams into a combined one.)  Of course, I want a type-level guarantee that there is one and only one handler per event type (for whatever set of event types I happen to want to use), and I want to know that any events that may get produced by the handlers will also be handled.  Essentially, the process of designing the simulator boils down to appending handlers together to make one big one, and running the simulator is folding `switch` over the stream of events on the handler.  It's still a prototype, but data-diverse has definitely been super helpful.

**Comment by louispan** [comment]
That sounds cool. I'd love to have a look at it one day (if possible).

I'm glad data-diverse is being used. You are the first user beside myself that I'm aware of. Because of the low number of users, I tend to just make breaking changes and just increment a major version number, but hopefully the api of data-diverse is getting more stable so it should be easy to upgrade between versions.

I created data-diverse because I wanted to experiment with a way of composing web page widgets. The main idea is to add builders that know how to create bits of a `Many`, and handlers that know how to handle a particular event in `Which` and modify the `Many` state. GHCJS and React integration makes it a lot harder to do nicely though. It's still very much in flux at the moment, but I'll let you know when I get it working.

**Comment by louispan** [comment]
Fixed in https://github.com/louispan/data-diverse/commit/225079e3ee1e85dd4264687575fd202dd0ffbffd
v0.11.0.0 uploaded to hackage http://hackage.haskell.org/package/data-diverse-0.11.0.0
