### ISSUE TITLE
Use Int or Word16 over Integer (KnownNat)

### ISSUE THREAD

**Issue by reactormonk** [louispan/data-distinct#8]
Apparently [GHC is terrible at optimizing Integers](https://ghc.haskell.org/trac/ghc/wiki/Plugins/TypeChecker/RowTypes/Coxswain#InefficientNatdictionaries), so switching to e.g. https://github.com/VinylRecords/Vinyl/blob/a5ffd10fbc747c5366ae9806e61bf45f78c3eb33/Data/Vinyl/TypeLevel.hs#L24 might be beneficial.

**Comment by louispan** [comment]
Thanks for the tip! I'll definitely look into this.

**Comment by louispan** [comment]
@reactormonk, what do you think of my changes in https://github.com/louispan/data-diverse/commit/e5a37593dd2fdc203f80671c6f5503eda39b5392#diff-cdf46e7019f0efa12eb0f0a041231ee1R22?

I'm using overlapping instances in order to reuse the GHC.TypeLit Nat, instead of defining my own. It's a less intrusive change in my library since I use the type operator '+'.

If you are happy with this change, I'll upload a v5.0.0.0 into Hackage

**Comment by louispan** [comment]
Released http://hackage.haskell.org/package/data-diverse-4.5.0.0
https://github.com/louispan/data-diverse/commit/96be655fe74a270d85de632ed45a7d37aa8a8853

**Comment by reactormonk** [comment]
You're too fast. Thanks!
